export const urls = {
	index: '/',
	signup: 'https://signup.bthackathon.com',
	y24Index: '/Y24/',
	y24Photos: '/Y24/photos',
	y24Sponsors: '/Y24/sponsors',
	y25Index: '/Y25/',
	y25Demos: '/Y25/demos',
	y25Photos: '/Y25/photos',
	y25Sponsors: '/Y25/sponsors',
	y25Prizes: '/Y25/prizes',
	y25Rubric: '/Y25/rubric',
	y26Index: '/Y26/',
	y26Program: '/Y26/program',
	y26Prizes: '/Y26/prizes',
	y26Rubric: '/Y26/rubric',
	y26Sponsors: '/Y26/sponsors',
	y26ProgramAd: '/Y26/program/ad',
	y26EventSummary:
		'https://raw.githubusercontent.com/mbryzek/hackathon-static/refs/heads/main/2026/2026-BTCSP-Hackathon-Event-Summary.pdf',
	mission: '/mission',
	donate: '/donate',
	press: '/press',
	contact: '/contact',

	// Voting routes
	vote: '/vote',
	voteEvent: (eventKey: string) => `/vote/${eventKey}`,
	voteThanks: (eventKey: string) => `/vote/${eventKey}/thanks`,

	// Admin routes
	voteAdminLogin: '/vote/admin/login',
	voteAdmin: '/vote/admin',
	voteAdminEventsNew: '/vote/admin/events/new',
	voteAdminEvent: (id: string) => `/vote/admin/events/${id}`,
	voteAdminEventProjects: (id: string) => `/vote/admin/events/${id}/projects`,
	voteAdminEventCodes: (id: string) => `/vote/admin/events/${id}/codes`,
	voteAdminEventResults: (id: string) => `/vote/admin/events/${id}/results`,
	voteAdminEventProjectsBulk: (id: string) => `/vote/admin/events/${id}/projects/bulk`,
} as const;
